# Generated by Django 4.0.4 on 2022-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2, null=True)),
            ],
        ),
    ]
