# Generated by Django 4.0.4 on 2022-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotuser',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2, null=True),
        ),
    ]
